# Generated by Django 4.2.28 on 2026-03-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_marketprice_alter_stock_ticker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField(blank=True, null=True)),
                ('turnover', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Portfolio.stock')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='MarketPrice',
        ),
    ]
